<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.0.8</Version>
    <Authors>zysilm</Authors>
    <Description>Experimental independent bone-following portrait camera.</Description>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RepoUrl>https://github.com/zysilm/DynamicPortrait</RepoUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.21.0" />
    <None Include="../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../THIRD_PARTY_NOTICES.md" Link="THIRD_PARTY_NOTICES.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
